### ISSUE TITLE
bug: order of historical messages in chat2

### ISSUE THREAD

**Issue by staheri14** [status-im/nwaku#1111]
### Problem
In chat2, the store messages should be displayed in ASC order so the newest messages appear at the bottom. However, it is not the case right now.

### Impact
Not critical, a good to have.

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Run 'make chat2' followed by `./build/chat2 --fleet:test` to see the historical messages, spot their timestamp to see they are shown in DSC order.

### Expected behavior
Recent messages are better to be displayed at the bottom.

### Screenshots/logs
NA

### nwaku version/commit hash

`v0.11-14-gecf4ba`

### Additional context
Bug was reported during rln-chat2 testnet1 https://github.com/status-im/nwaku/issues/1069

**Comment by jm-clius** [comment]
@staheri14 since this issue was reported during the rln testnet, the test fleet has been updated with what I believe to be a fix for the message order problem. If I follow the reproduction steps I always retrieve messages in ASC order with newest at the bottom? Can you check if the issue still occurs for you? Note that the number of retrieved messages are inconsistent and being investigated as part of https://github.com/status-im/nwaku/issues/1111, but the order seems fine.

**Comment by staheri14** [comment]
@jm-clius Thanks for your comment, just checked the master branch and confirmed that the message order is now correct.
