### ISSUE TITLE
bug: --log-level flag appears to be ignored

### ISSUE THREAD

**Issue by jakubgs** [status-im/nwaku#1197]
### Problem
The `--log-level` flag does nothing for `wakunode2`:
```
 # ./wakunode2 --help | grep log-level
 --log-level               Sets the log level. [=LogLevel.INFO].
 # systemctl cat nwaku | grep log
  --log-level=info \
 # journalctl -o cat -au nwaku | grep DBG | wc -l
612
```

### Impact
What's the point of defining a flag that does nothing?

**Comment by alrevuelta** [comment]
Accidentally found the issue here when adding `log-level` to #754. Long story short we are missing `-d:chronicles_runtime_filtering:on` flag when building. Without that, `setLogLevel()` is ignored. Note also that `chronicles_log_level` should be set to `DEBUG`, otherwise `setLogLevel(DEBUG)` won't work.

Taken from [chronicles_runtime_filtering](https://github.com/status-im/nim-chronicles/blob/e6a90dcfa2c086711915ab4ceb56c8ef16916dc5/README.md#chronicles_runtime_filtering) docs:

> This option enables the run-filtering capabilities of Chronicles. The run-time filtering is controlled through the procs setLogLevel and setTopicState:

> The log levels available at runtime - and therefor to setLogLevel() - are those greater than or equal to the one set at compile time by chronicles_log_level.

Will prepare a fix for it.
