### ISSUE TITLE
Node crashes with db-path enabled on restart when nodekey is not specified

### ISSUE THREAD

**Issue by dmh1974** [status-im/nwaku#962]
Without nodekey specified the node generates a new unique key with each restart. 
I infer this is somehow linked to the failure (perhaps in db grants and/or query of keys/data related to the node key).

I can get the node started again by first deleting the db (path included).. the node then creates a new db on next startup without issue

Also, it does not appear to be an issue when specifying a nodekey param... node reboots and mounts previously created db without issue.

Here are the switches to reproduce the issue... (note, does not include nodekey param)
--store=true --persist-messages=true --db-path="./dbs/db1"

**Comment by kaiserd** [comment]
This error was most likely due to competing TPC port issues. `port-shift` was not set. (we could confirm this)
I could not reproduce the error with `-store=true --persist-messages=true --db-path="./dbs/db1"`

However, a (maybe unrelated) DB migration related error has been reported in the discord:
`migration failed   topics="wakunode.setup" tid=1 file=waku_setup.nim:113 error="no suitable migration scripts"`

Not enough context for now. We will try to reproduce the DB related error.

**Comment by dmh1974** [comment]
indeed we were able to get my node started by applying an additional -port-shift=1 switch after an errored start

hoever, i think its important to note that performing an rm -rf ./dbs/db1 will also get the node to start

also, one bit i forgot to mention - between restarts i am sending a few test messages to the node

**Comment by dmh1974** [comment]
fyi, i am defenitely leaning toward graceful port handling as the cause, as its still possible my db deduction could have just been a coincidence of sorts. cntrl-c should handle port closures gracefuly, and starting should handle clearing them gracefully before use

**Comment by kaiserd** [comment]
> also, one bit i forgot to mention in the original ticket and shared out of band with @kaiserd - between restarts i am sending a few test messages to the node

I also did that in my tests, but could not replicate the DB error. (including checking that the DB was not empty)

> fyi, i am defenitely leaning toward graceful port handling as the cause, as its still possible my db deduction could have just been a coincidence of sorts. cntrl-c should handle port closures gracefuly, and starting should handle clearing them gracefully before use

I will look in to this now and open a new issue for the port freeing.

Thanks for helping in the investigation @dmh1974 :)

**Comment by kaiserd** [comment]
There is already an issue regarding ports not being freed: 959

**Comment by kaiserd** [comment]
`migration failed topics="wakunode.setup" tid=1 file=waku_setup.nim:113 error="no suitable migration scripts"` 

After further investigation I assume, this is not the real problem of the related crash either, just a misleading warning.
-> I will open a new issue for this once we have more context.

I think, we can close this issue. The problem that was the reason for opening this issue is covered in #959.
@dmh1974 wdyt?

**Comment by dmh1974** [comment]
agreed! i shall close the issue!
